repos:
  # not compatible with black right now
  #- repo: https://github.com/timothycrosley/isort
  #  rev: master
  #  hooks:
  #    - id: isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/python/black
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3.11

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v0.770
  #  hooks:
  #    - id: mypy
  #      language_version: python3.7

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: (^tests|^alembic)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: fix-encoding-pragma
      #- id: flake8

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
